title: Hasebul Hassan Chowdhury
logo: /assets/img/hasebul.jpeg
description: I’m a passionate Software Engineer with a strong foundation in backend and full-stack development. Currently working at Cefalo Bangladesh Ltd., I specialize in building scalable and maintainable applications using Java, Spring Boot, Angular, and PostgreSQL. My work is guided by performance optimization, clean architecture, and a continuous drive to learn and improve.
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
